### ISSUE TITLE
Computing satisfying probability while the solver contains no clause

### ISSUE THREAD

**Issue by nianzelee** [nianzelee/ssatABC#2]
In [`src/ssat/core/ssatERSolve.cc:SsatSolver::erSolve2SSAT`](https://github.com/nianzelee/ssatABC/blob/e036412bf8bc6ee7686bc9c74cdb0b1dece8dfbe/src/ssat/core/ssatERSolve.cc), after `_s2` gives an assignment to exist variables, `_s1` would solve the matrix under the given assumption. If the matrix is satisfiable under the assumption, model counting is used to compute the satisfying probability of the residual formula. 

Question: when there is no clause left in `_s1` after the assumption, is it true that the satisfying probability equals 1?
>No, the satisfying probability should be the product of probabilities of random variables based on their assignments.

Currently this is considered as a special case to handle, but a solution has not yet been developed.
https://github.com/nianzelee/ssatABC/blob/e036412bf8bc6ee7686bc9c74cdb0b1dece8dfbe/src/ssat/core/ssatERSolve.cc#L115-L120

**Comment by nianzelee** [comment]
In commit 2a26cac a quick fix is done for the situation when there is no clause left after simplification by SAT solver. In this situation, the satisfying probability is the product of the probabilities of random variables, based on their assignments.

The remaining question is: can this fix be used in the main ER-SSAT loop? That is, when `_s2` assigns exist variables and `_s1` becomes empty under this assignment, can we compute the probability in the same way? What about the learnt clause?

**Comment by nianzelee** [comment]
In commit d6f2790, the original fix is moved into `SsatSolver::erSolveWMC`. As explained in the commit message, the learning process will work fine in such situation, so the only thing to change is to handle the computation of satisfying probability.

@yen-shi : would you please let me know if you agree with this fix? If you agree then this issue can be closed and this [bug-fixing branch](https://github.com/nianzelee/ssatABC/tree/d6f279007ec0307ecca17e672da637d882ad7845) can be merged back to master.

**Comment by yen-shi** [comment]
Just left a comment on the commit, and it looks good to me.

**Comment by nianzelee** [comment]
The fix has been integrated into master (with rebase). The bug-fixing branch will be deleted and this issue will be closed.
