### ISSUE TITLE
Static Binary of ssatABC

### ISSUE THREAD

**Issue by mahi045** [nianzelee/ssatABC#20]
I am interested in building ssatABC **statically**. How I can modify the `Makefile` to build it statically?

**Comment by nianzelee** [comment]
Please have a look at this [issue](https://github.com/NTU-ALComLab/MCC2021/issues/3).

**Comment by mahi045** [comment]
Can I ask you whether the [model-counting-competition](https://github.com/NTU-ALComLab/ssatABC/tree/model-counting-competition) branch makefile compiles statically?

**Comment by nianzelee** [comment]
Yes, but you need to compile it with `make ABC_USE_NO_READLINE=1`.
(Have a look at ABC's [readme](https://github.com/berkeley-abc/abc#troubleshooting).)

You can verify the resulting binary with `ldd bin/abc`. It should print `not a dynamic executable`. This works on my Ubuntu 20.04 machine.

If you have an very old environment, you may need to specify more options for `gcc`, cf. this [post](https://github.com/NTU-ALComLab/MCC2021/issues/3#issue-883451846).

If you just need a static binary, you can download one [here](https://github.com/NTU-ALComLab/MCC2021/blob/master/bin/abc).

**Comment by mahi045** [comment]
Thank you @nianzelee. It is very helpful.
